# Generated by Django 6.0.3 on 2026-04-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnomolyFlag",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="InvoiceApproval",
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
        migrations.DeleteModel(
            name="VendorAnomolyHistory",
        ),
    ]
