# Generated by Django 6.0.3 on 2026-04-15 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0002_delete_anomolyflag_delete_invoice_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_normalized", models.CharField(max_length=200)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("pan", models.CharField(blank=True, max_length=10)),
                ("is_approved", models.BooleanField(default=False)),
                ("vendor_type", models.CharField(max_length=30)),
                (
                    "avg_invoice_amount",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("invoice_count", models.IntegerField(default=0)),
                ("last_renewal_date", models.DateField(null=True)),
                ("last_seat_count", models.IntegerField(null=True)),
                ("tds_section", models.CharField(blank=True, max_length=10)),
                ("msme_registered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ref_no", models.CharField(blank=True, max_length=30, unique=True)),
                ("filed_on_behalf", models.BooleanField(default=False)),
                ("invoice_number", models.CharField(max_length=100)),
                ("invoice_date", models.DateField()),
                (
                    "pre_gst_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "cgst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "sgst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "igst",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("tds_section", models.CharField(blank=True, max_length=10)),
                (
                    "tds_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("business_purpose", models.TextField()),
                (
                    "_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("AUTO_REJECT", "Auto Reject"),
                            ("PENDING_L1", "Pending L1"),
                            ("PENDING_L2", "Pending L2"),
                            ("PENDING_HOD", "Pending HoD"),
                            ("PENDING_FIN_L1", "Pending Finance L1"),
                            ("PENDING_FIN_L2", "Pending Finance L2"),
                            ("PENDING_FIN_HEAD", "Pending Finance Head"),
                            ("QUERY_RAISED", "Query Raised"),
                            ("REJECTED", "Rejected"),
                            ("APPROVED", "Approved"),
                            ("PENDING_D365", "Pending D365"),
                            ("BOOKED_D365", "Booked in D365"),
                            ("POSTED_D365", "Posted in D365"),
                            ("PAID", "Paid"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_column="status",
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("current_step", models.IntegerField(blank=True, null=True)),
                (
                    "anomaly_severity",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("d365_document_no", models.CharField(blank=True, max_length=100)),
                ("d365_posted_at", models.DateTimeField(null=True)),
                ("d365_paid_at", models.DateTimeField(null=True)),
                ("d365_payment_utr", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(null=True)),
                ("approved_at", models.DateTimeField(null=True)),
                (
                    "filer_on_behalf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filed_on_behalf_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "replaces_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invoices.expense",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseApprovalStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level", models.IntegerField()),
                ("role_required", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("QUERIED", "Queried"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("sla_due_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(null=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("anomaly_override_reason", models.TextField(blank=True)),
                (
                    "actual_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acted_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegated_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_steps",
                        to="invoices.expense",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileRef",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raised_at_step", models.IntegerField()),
                ("question", models.TextField()),
                ("response", models.TextField(blank=True)),
                ("raised_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(null=True)),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="invoices.expense",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raised_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attachments",
                    models.ManyToManyField(blank=True, to="invoices.fileref"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expense",
            name="evidence_files",
            field=models.ManyToManyField(
                blank=True, related_name="evidence_for", to="invoices.fileref"
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="invoice_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_for",
                to="invoices.fileref",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="invoices.vendor"
            ),
        ),
        migrations.CreateModel(
            name="VendorL1Mapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "l1_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="l1_mappings",
                        to="invoices.vendor",
                    ),
                ),
            ],
            options={
                "unique_together": {("vendor", "l1_user")},
            },
        ),
    ]
