# Generated by Django 6.0.3 on 2026-04-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_vendor_name_normalized_and_more"),
        ("invoices", "0002_approvalauthority_expensequery_ai_suggestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="core.vendor",
            ),
        ),
    ]
