# Generated by Django 6.0.3 on 2026-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_alter_expense_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="gstin",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
