# Generated by Django 6.0.4 on 2026-04-16 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="ocr_confidence",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="ocr_raw",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="ocr_task_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="expense",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="vendor",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="vendor",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="vendor",
            name="bank_ifsc",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="vendor",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="vendor",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("BLACKLISTED", "Blacklisted"),
                    ("INACTIVE", "Inactive"),
                ],
                default="PENDING_APPROVAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="business_purpose",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="expenseapprovalstep",
            name="sla_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="vendor_type",
            field=models.CharField(default="general", max_length=30),
        ),
    ]
