# Generated by Django 6.0.3 on 2026-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0005_ai_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="d365_push_error",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
