# Generated by Django 6.0.3 on 2026-05-05 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _apply_idempotent(apps, schema_editor):
    conn = schema_editor.connection
    with conn.cursor() as cur:
        cur.execute("""
            CREATE TABLE IF NOT EXISTS invoices_monthlyfinancialsummary (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                month_key varchar(7) NOT NULL UNIQUE,
                month_start date NOT NULL,
                summary_payload jsonb NOT NULL DEFAULT '{}',
                created_at timestamptz NOT NULL,
                generated_at timestamptz NOT NULL,
                generated_by_id integer
                    REFERENCES core_user(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED
            )
        """)
        cur.execute("""
            CREATE INDEX IF NOT EXISTS invoices_mo_month_s_02acbd_idx
            ON invoices_monthlyfinancialsummary (month_start)
        """)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0006_expense_d365_push_error"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(_apply_idempotent, _noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="MonthlyFinancialSummary",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("month_key", models.CharField(db_index=True, max_length=7, unique=True)),
                        ("month_start", models.DateField()),
                        ("summary_payload", models.JSONField(default=dict)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("generated_at", models.DateTimeField(auto_now=True)),
                        (
                            "generated_by",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="generated_monthly_summaries",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "ordering": ["-month_start"],
                        "indexes": [
                            models.Index(fields=["month_start"], name="invoices_mo_month_s_02acbd_idx")
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
