# Generated by Django 6.0.3 on 2026-05-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0007_monthlyfinancialsummary"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="monthlyfinancialsummary",
            new_name="invoices_mo_month_s_02acbd_idx",
            old_name="invoices_mo_month_s_e26ff5_idx",
        ),
    ]
