# Generated by Django 6.0.3 on 2026-05-07 06:50

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_groupprofile_and_more"),
        ("invoices", "0007_monthlyfinancialsummary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ARCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("gstin", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("payment_terms", models.CharField(default="Net 30", max_length=20)),
                ("credit_limit", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ar_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ARInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ref_no", models.CharField(blank=True, max_length=30, unique=True)),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                ("issue_date", models.DateField(default=datetime.date.today)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("payment_terms", models.CharField(default="Net 30", max_length=20)),
                ("pre_gst_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("cgst", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("sgst", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("igst", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Unpaid"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("DISPUTED", "Disputed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UNPAID",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ar_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ar_invoices",
                        to="invoices.arcustomer",
                    ),
                ),
                (
                    "invoice_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ar_invoices",
                        to="core.fileref",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="ARPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount_received", models.DecimalField(decimal_places=2, max_digits=18)),
                ("received_at", models.DateField(default=datetime.date.today)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("NEFT", "NEFT"),
                            ("RTGS", "RTGS"),
                            ("IMPS", "IMPS"),
                            ("CHEQUE", "Cheque"),
                            ("UPI", "UPI"),
                            ("CASH", "Cash"),
                            ("OTHER", "Other"),
                        ],
                        default="NEFT",
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoices.arinvoice",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_ar_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddIndex(
            model_name="arcustomer",
            index=models.Index(fields=["name"], name="invoices_ar_name_12046b_idx"),
        ),
        migrations.AddIndex(
            model_name="arcustomer",
            index=models.Index(fields=["status"], name="invoices_ar_status_befffa_idx"),
        ),
        migrations.AddIndex(
            model_name="arinvoice",
            index=models.Index(
                fields=["customer", "status"], name="invoices_ar_custome_caa121_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arinvoice",
            index=models.Index(
                fields=["due_date", "status"], name="invoices_ar_due_dat_6cd921_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="arinvoice",
            index=models.Index(fields=["issue_date"], name="invoices_ar_issue_d_ed9a4f_idx"),
        ),
    ]
