# Generated by Django 6.0.4 on 2026-04-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("finance_admin", "Finance Admin"),
                    ("finance_manager", "Finance Manager"),
                    ("dept_head", "Department Head"),
                    ("employee", "Employee"),
                    ("vendor", "Vendor"),
                ],
                default="employee",
                max_length=30,
            ),
        ),
    ]
