# Generated by Django 5.2.13 on 2026-04-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cfo', 'CFO'), ('finance_admin', 'Finance Admin'), ('finance_manager', 'Finance Manager'), ('dept_head', 'Department Head'), ('employee', 'Employee'), ('vendor', 'Vendor')], default='employee', max_length=30),
        ),
    ]
