# Generated by Django 6.0.3 on 2026-04-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_fileref_table_alter_vendor_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="name_normalized",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="avg_invoice_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=18, null=True
            ),
        ),
    ]
