# Generated by Django 6.0.3 on 2026-04-29 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_enhance_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("sub_text", models.CharField(blank=True, default="", max_length=100)),
                ("action", models.CharField(blank=True, default="", max_length=100)),
                ("entity_type", models.CharField(blank=True, default="", max_length=50)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_read"], name="core_notifi_user_id_cb8f07_idx")
                ],
            },
        ),
    ]
