# Generated by Django 6.0.3 on 2026-05-06 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0009_chatsession_aicopilotlog_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("policies", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "core_group_profile",
            },
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="core_notifi_user_id_cb8f07_idx",
        ),
        migrations.AddField(
            model_name="vendor",
            name="bc_vendor_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="profile", to="auth.group"
            ),
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
