# Generated by Django 6.0.3 on 2026-05-05 18:53

import django.db.models.deletion
from django.db import migrations, models


def _apply_idempotent(apps, schema_editor):
    conn = schema_editor.connection
    with conn.cursor() as cur:
        # GroupProfile table (may already exist from old branch)
        cur.execute("""
            CREATE TABLE IF NOT EXISTS core_group_profile (
                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                policies jsonb NOT NULL DEFAULT '{}',
                group_id integer NOT NULL UNIQUE
                    REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED
            )
        """)

        # Drop old core.Notification index if it still exists
        cur.execute("""
            DROP INDEX IF EXISTS core_notifi_user_id_cb8f07_idx
        """)

        # Add bc_vendor_no if missing
        cur.execute("""
            ALTER TABLE core_vendor
            ADD COLUMN IF NOT EXISTS bc_vendor_no varchar(50) NOT NULL DEFAULT ''
        """)

        # Drop old core.Notification table if it still exists
        cur.execute("DROP TABLE IF EXISTS core_notification CASCADE")


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0009_chatsession_aicopilotlog_session"),
    ]

    operations = [
        migrations.RunPython(_apply_idempotent, _noop),
        # State-only operations so Django's ORM state stays correct
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="GroupProfile",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("policies", models.JSONField(blank=True, default=dict)),
                    ],
                    options={
                        "db_table": "core_group_profile",
                    },
                ),
                migrations.AddField(
                    model_name="groupprofile",
                    name="group",
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="auth.group",
                    ),
                ),
                migrations.AddField(
                    model_name="vendor",
                    name="bc_vendor_no",
                    field=models.CharField(blank=True, max_length=50),
                ),
                migrations.DeleteModel(name="Notification"),
            ],
            database_operations=[],
        ),
    ]
