# Generated by Django 6.0.3 on 2026-05-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_chatsession_aicopilotlog_session"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="core_notifi_user_id_cb8f07_idx",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
