# Generated by Django 6.0.3 on 2026-04-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CashFlowForecast",
        ),
        migrations.DeleteModel(
            name="DailyCashFlow",
        ),
        migrations.DeleteModel(
            name="ScenarioOverlay",
        ),
    ]
