# Generated by Django 6.0.3 on 2026-04-15 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpensePolicyLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("category", models.CharField(max_length=60)),
                ("grade_min", models.CharField(max_length=10)),
                ("grade_max", models.CharField(max_length=10)),
                ("daily_limit", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("per_item_limit", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                (
                    "auto_approve_threshold",
                    models.DecimalField(decimal_places=2, default=500, max_digits=10),
                ),
            ],
            options={
                "db_table": "expenses_policylimit",
            },
        ),
    ]
